import { Assistencia } from '@/types/assistencia';

export const mockAssistencias: Assistencia[] = [
  {
    id: 'mock-001',
    pedido: 'PED-2025-0001',
    lote: 'LT-001',
    dataEmissao: '2025-01-08',
    cliente: 'Construtora Horizonte Ltda',
    cidadeUF: 'São Paulo/SP',
    estado: 'SP',
    nfAt: 'NFAT-10001',
    nfVenda: 'NFV-55201',
    item: 'IT-3042',
    descricaoItem: 'Janela de Correr 2 Folhas 1,20x1,00m - Alumínio Branco',
    quantidade: 12,
    causaAssistencia: 'Perfil de arremate com defeito de fábrica apresentando dobramento irregular',
    acoesCorretivas: 'Substituição dos perfis defeituosos por novos do mesmo lote de produção',
    motivoAssistencia: 'Defeito de Fabricação',
    motoristaResponsavel: 'Carlos Eduardo Souza',
    setor: 'Técnico',
    observacaoPedido: 'Entrega urgente solicitada pelo cliente. Obra com prazo fechado.',
    dataFinalizacao: '2025-01-20',
    status: 'Finalizado',
    modoEnvio: 'Transportadora',
    emitirRncPdcva: true,
    observacoes: 'RNC emitida em 10/01/2025. Cliente confirmou recebimento e aprovação das peças.',
    createdAt: '2025-01-08T08:30:00.000Z',
    updatedAt: '2025-01-20T17:00:00.000Z',
  },
  {
    id: 'mock-002',
    pedido: 'PED-2025-0002',
    lote: 'LT-002',
    dataEmissao: '2025-01-15',
    cliente: 'Incorporadora Vila Nova S.A.',
    cidadeUF: 'Campinas/SP',
    estado: 'SP',
    nfAt: 'NFAT-10002',
    nfVenda: 'NFV-55345',
    item: 'IT-2201',
    descricaoItem: 'Porta de Entrada Social 0,90x2,10m - Alumínio Preto Fosco',
    quantidade: 4,
    causaAssistencia: 'Fechadura com travamento irregular comprometendo abertura/fechamento da porta',
    acoesCorretivas: 'Regulagem do mecanismo de fechadura e substituição do conjunto de borrachas de vedação',
    motivoAssistencia: 'Falha de Montagem',
    motoristaResponsavel: 'Roberto Almeida',
    setor: 'Técnico',
    observacaoPedido: 'Empreendimento de alto padrão, exige visita técnica presencial.',
    dataFinalizacao: '',
    status: 'Em Andamento',
    modoEnvio: 'Frota Própria',
    emitirRncPdcva: false,
    observacoes: 'Técnico agendado para visita na segunda-feira. Cliente ciente.',
    createdAt: '2025-01-15T09:00:00.000Z',
    updatedAt: '2025-01-18T14:20:00.000Z',
  },
  {
    id: 'mock-003',
    pedido: 'PED-2025-0003',
    lote: 'LT-001',
    dataEmissao: '2025-01-22',
    cliente: 'Residencial Araucária Condomínio',
    cidadeUF: 'Curitiba/PR',
    estado: 'PR',
    nfAt: 'NFAT-10003',
    nfVenda: 'NFV-55412',
    item: 'IT-1105',
    descricaoItem: 'Esquadria de Vidro Temperado 8mm - 2,00x1,50m',
    quantidade: 6,
    causaAssistencia: 'Vidro com risco superficial visível identificado após instalação pelo cliente',
    acoesCorretivas: 'Aguardando chegada de vidros substitutos do fornecedor para reposição',
    motivoAssistencia: 'Dano no Transporte',
    motoristaResponsavel: 'Marcos Pereira',
    setor: 'Logística',
    observacaoPedido: 'Produto frágil. Conferir embalagem antes do reenvio.',
    dataFinalizacao: '',
    status: 'Aguardando Peças',
    modoEnvio: 'Transportadora',
    emitirRncPdcva: true,
    observacoes: 'Sinistro aberto junto à transportadora. Protocolo #2025-0445.',
    createdAt: '2025-01-22T10:15:00.000Z',
    updatedAt: '2025-01-25T11:30:00.000Z',
  },
  {
    id: 'mock-004',
    pedido: 'PED-2025-0004',
    lote: 'LT-003',
    dataEmissao: '2025-02-03',
    cliente: 'Engenharia & Projetos Belo Horizonte',
    cidadeUF: 'Belo Horizonte/MG',
    estado: 'MG',
    nfAt: 'NFAT-10004',
    nfVenda: 'NFV-55589',
    item: 'IT-4411',
    descricaoItem: 'Guarda-corpo em Alumínio e Vidro - Linear 10m',
    quantidade: 2,
    causaAssistencia: 'Perfis de fixação com medidas divergentes do projeto executivo aprovado',
    acoesCorretivas: 'Refabricação dos perfis conforme medidas do projeto. Prazo de 10 dias úteis.',
    motivoAssistencia: 'Erro de Especificação',
    motoristaResponsavel: 'José Ferreira',
    setor: 'Comercial',
    observacaoPedido: 'Responsável técnico da obra: Eng. Paulo Mendes. Fone: (31) 99123-4567',
    dataFinalizacao: '',
    status: 'Em Andamento',
    modoEnvio: 'Transportadora',
    emitirRncPdcva: true,
    observacoes: 'Reunião com cliente agendada para apresentação da solução proposta.',
    createdAt: '2025-02-03T08:00:00.000Z',
    updatedAt: '2025-02-06T16:45:00.000Z',
  },
  {
    id: 'mock-005',
    pedido: 'PED-2025-0005',
    lote: 'LT-004',
    dataEmissao: '2025-02-10',
    cliente: 'Supermercados Rede Forte',
    cidadeUF: 'Porto Alegre/RS',
    estado: 'RS',
    nfAt: 'NFAT-10005',
    nfVenda: 'NFV-55701',
    item: 'IT-5523',
    descricaoItem: 'Porta Automática de Correr - 2 Folhas 1,60x2,20m',
    quantidade: 1,
    causaAssistencia: 'Sensor de presença com falha intermitente causando paradas não programadas',
    acoesCorretivas: 'Substituição do módulo de controle eletrônico e recalibração dos sensores',
    motivoAssistencia: 'Defeito de Fabricação',
    motoristaResponsavel: 'Anderson Lima',
    setor: 'Técnico',
    observacaoPedido: 'Loja em funcionamento 24h. Intervenção somente após as 22h.',
    dataFinalizacao: '2025-02-18',
    status: 'Finalizado',
    modoEnvio: 'Frota Própria',
    emitirRncPdcva: false,
    observacoes: 'Serviço realizado no período noturno sem interrupção das operações. Cliente satisfeito.',
    createdAt: '2025-02-10T11:30:00.000Z',
    updatedAt: '2025-02-18T23:50:00.000Z',
  },
  {
    id: 'mock-006',
    pedido: 'PED-2025-0006',
    lote: 'LT-005',
    dataEmissao: '2025-02-17',
    cliente: 'Hospital Santa Lucia',
    cidadeUF: 'Brasília/DF',
    estado: 'DF',
    nfAt: 'NFAT-10006',
    nfVenda: 'NFV-55823',
    item: 'IT-6612',
    descricaoItem: 'Janela Pivotante em Alumínio com Vidro Laminado - 0,80x1,20m',
    quantidade: 30,
    causaAssistencia: 'Vedação insuficiente permitindo infiltração de ar e ruído externo nas alas de internação',
    acoesCorretivas: 'Aplicação de borrachas de vedação de alta performance e ajuste das dobradiças',
    motivoAssistencia: 'Especificação Inadequada',
    motoristaResponsavel: 'Luiz Antonio Campos',
    setor: 'Técnico',
    observacaoPedido: 'Ambiente hospitalar. Equipe deve utilizar EPI completo e respeitar normas sanitárias.',
    dataFinalizacao: '',
    status: 'Aguardando Cliente',
    modoEnvio: 'Frota Própria',
    emitirRncPdcva: true,
    observacoes: 'Aguardando liberação da gestão hospitalar para início dos trabalhos. Contato: Adm. Fernanda Costa.',
    createdAt: '2025-02-17T09:00:00.000Z',
    updatedAt: '2025-02-20T10:00:00.000Z',
  },
  {
    id: 'mock-007',
    pedido: 'PED-2025-0007',
    lote: 'LT-003',
    dataEmissao: '2025-02-24',
    cliente: 'Shopping Center Orion',
    cidadeUF: 'Goiânia/GO',
    estado: 'GO',
    nfAt: 'NFAT-10007',
    nfVenda: 'NFV-55944',
    item: 'IT-7701',
    descricaoItem: 'Fachada em ACM - Painel 4mm Branco Brilhante - 50m²',
    quantidade: 1,
    causaAssistencia: 'Descolamento de painel na fachada principal após fortes chuvas',
    acoesCorretivas: 'Revisão completa de todos os fixadores e reaplicação com cola estrutural bicomponente',
    motivoAssistencia: 'Falha de Montagem',
    motoristaResponsavel: 'Ricardo Santos',
    setor: 'Técnico',
    observacaoPedido: 'Interditar área abaixo do painel até conclusão dos reparos. Risco de queda.',
    dataFinalizacao: '',
    status: 'Aberto',
    modoEnvio: 'Frota Própria',
    emitirRncPdcva: true,
    observacoes: 'Laudo técnico fotográfico elaborado. Pendente aprovação do orçamento de reparo.',
    createdAt: '2025-02-24T07:45:00.000Z',
    updatedAt: '2025-02-24T15:30:00.000Z',
  },
  {
    id: 'mock-008',
    pedido: 'PED-2025-0008',
    lote: 'LT-006',
    dataEmissao: '2025-03-03',
    cliente: 'Escola Estadual Dom Pedro II',
    cidadeUF: 'Salvador/BA',
    estado: 'BA',
    nfAt: 'NFAT-10008',
    nfVenda: 'NFV-56012',
    item: 'IT-2310',
    descricaoItem: 'Porta de Abrir com Visor em Alumínio - 0,90x2,10m',
    quantidade: 15,
    causaAssistencia: 'Dobradiças apresentando oxidação prematura em ambiente litorâneo',
    acoesCorretivas: 'Substituição por dobradiças de aço inox 316 com tratamento anti-salino',
    motivoAssistencia: 'Especificação Inadequada',
    motoristaResponsavel: 'Fabrício Oliveira',
    setor: 'Técnico',
    observacaoPedido: 'Escola em período letivo. Serviço preferencial aos finais de semana.',
    dataFinalizacao: '2025-03-15',
    status: 'Finalizado',
    modoEnvio: 'Transportadora',
    emitirRncPdcva: false,
    observacoes: 'Serviço concluído no sábado. Direção da escola assinou termo de recebimento.',
    createdAt: '2025-03-03T08:30:00.000Z',
    updatedAt: '2025-03-15T16:00:00.000Z',
  },
  {
    id: 'mock-009',
    pedido: 'PED-2025-0009',
    lote: 'LT-006',
    dataEmissao: '2025-03-07',
    cliente: 'Indústria Metalúrgica Norteço',
    cidadeUF: 'Manaus/AM',
    estado: 'AM',
    nfAt: 'NFAT-10009',
    nfVenda: 'NFV-56145',
    item: 'IT-8802',
    descricaoItem: 'Cobertura em Policarbonato Alveolar 10mm - 120m²',
    quantidade: 1,
    causaAssistencia: 'Amarelamento e perda de transparência do policarbonato em menos de 1 ano',
    acoesCorretivas: 'Análise do lote e substituição por material com proteção UV adequada para região amazônica',
    motivoAssistencia: 'Defeito de Fabricação',
    motoristaResponsavel: 'Thiago Barbosa',
    setor: 'Qualidade',
    observacaoPedido: 'Frete aéreo para Manaus. Verificar disponibilidade e custo antes de emitir NF.',
    dataFinalizacao: '',
    status: 'Em Andamento',
    modoEnvio: 'Transportadora',
    emitirRncPdcva: true,
    observacoes: 'Amostras do material defeituoso enviadas ao laboratório para laudo técnico. Prazo: 7 dias.',
    createdAt: '2025-03-07T10:00:00.000Z',
    updatedAt: '2025-03-10T09:15:00.000Z',
  },
  {
    id: 'mock-010',
    pedido: 'PED-2025-0010',
    lote: 'LT-007',
    dataEmissao: '2025-03-10',
    cliente: 'Residências Premium Alto das Pedras',
    cidadeUF: 'Florianópolis/SC',
    estado: 'SC',
    nfAt: 'NFAT-10010',
    nfVenda: 'NFV-56278',
    item: 'IT-3301',
    descricaoItem: 'Sistema de Abertura Pantográfica - Janela 2,40x1,20m',
    quantidade: 8,
    causaAssistencia: 'Mecanismo de abertura com folga excessiva gerando ruído ao acionar',
    acoesCorretivas: 'Substituição dos braços pantográficos e ajuste fino de todos os mecanismos',
    motivoAssistencia: 'Desgaste Prematuro',
    motoristaResponsavel: 'Fernando Gomes',
    setor: 'Técnico',
    observacaoPedido: 'Condomínio fechado. Cadastrar veículo na portaria antes da visita técnica.',
    dataFinalizacao: '',
    status: 'Aberto',
    modoEnvio: 'Frota Própria',
    emitirRncPdcva: false,
    observacoes: 'Visita técnica inicial agendada para 18/03. Aguardando confirmação do síndico.',
    createdAt: '2025-03-10T14:00:00.000Z',
    updatedAt: '2025-03-11T08:00:00.000Z',
  },
  {
    id: 'mock-011',
    pedido: 'PED-2025-0011',
    lote: 'LT-007',
    dataEmissao: '2025-03-12',
    cliente: 'Clínica Odontológica Sorrir Bem',
    cidadeUF: 'Recife/PE',
    estado: 'PE',
    nfAt: 'NFAT-10011',
    nfVenda: 'NFV-56389',
    item: 'IT-1420',
    descricaoItem: 'Divisória em Vidro Laminado 10mm com Perfil de Alumínio',
    quantidade: 5,
    causaAssistencia: 'Silicone de acabamento com espaçamento irregular comprometendo a estética',
    acoesCorretivas: 'Remoção completa do silicone antigo e reaplicação com template de guia',
    motivoAssistencia: 'Falha de Montagem',
    motoristaResponsavel: 'Paulo Roberto Nunes',
    setor: 'Técnico',
    observacaoPedido: 'Clínica em funcionamento. Comunicar o técnico para agendar horário fora do expediente.',
    dataFinalizacao: '2025-03-20',
    status: 'Finalizado',
    modoEnvio: 'Motoboy',
    emitirRncPdcva: false,
    observacoes: 'Serviço realizado fora do horário comercial. Aceite do cliente recebido por e-mail.',
    createdAt: '2025-03-12T09:30:00.000Z',
    updatedAt: '2025-03-20T19:00:00.000Z',
  },
  {
    id: 'mock-012',
    pedido: 'PED-2025-0012',
    lote: 'LT-008',
    dataEmissao: '2025-03-14',
    cliente: 'Grupo Hoteleiro Atlântico',
    cidadeUF: 'Fortaleza/CE',
    estado: 'CE',
    nfAt: 'NFAT-10012',
    nfVenda: 'NFV-56501',
    item: 'IT-9901',
    descricaoItem: 'Esquadria Linha Suprema - Janela de Projetar 1,00x1,00m',
    quantidade: 120,
    causaAssistencia: 'Lote com variação de cor perceptível em relação ao padrão aprovado na mostra',
    acoesCorretivas: 'Análise colorimétrica em andamento. Possível substituição parcial do lote.',
    motivoAssistencia: 'Divergência de Especificação',
    motoristaResponsavel: 'Alexandre Costa',
    setor: 'Qualidade',
    observacaoPedido: 'Projeto de grande porte. Escalar para gerência antes de qualquer decisão sobre substituição.',
    dataFinalizacao: '',
    status: 'Aguardando Peças',
    modoEnvio: 'Transportadora',
    emitirRncPdcva: true,
    observacoes: 'Reunião com diretoria do grupo hoteleiro agendada para 25/03. Preparar apresentação.',
    createdAt: '2025-03-14T08:00:00.000Z',
    updatedAt: '2025-03-18T17:30:00.000Z',
  },
  {
    id: 'mock-013',
    pedido: 'PED-2025-0013',
    lote: 'LT-008',
    dataEmissao: '2025-03-17',
    cliente: 'Prefeitura Municipal de Londrina',
    cidadeUF: 'Londrina/PR',
    estado: 'PR',
    nfAt: 'NFAT-10013',
    nfVenda: 'NFV-56612',
    item: 'IT-5102',
    descricaoItem: 'Porta Corta-Fogo CF-60 com Barra Antipânico - 0,90x2,10m',
    quantidade: 10,
    causaAssistencia: 'Barra antipânico com trava não retornando à posição original após acionamento',
    acoesCorretivas: 'Substituição da mola interna da barra e lubrificação do mecanismo de travamento',
    motivoAssistencia: 'Defeito de Fabricação',
    motoristaResponsavel: 'Gilmar Ferreira',
    setor: 'Técnico',
    observacaoPedido: 'Produto de segurança. Emitir laudo técnico após conclusão do reparo.',
    dataFinalizacao: '',
    status: 'Em Andamento',
    modoEnvio: 'Frota Própria',
    emitirRncPdcva: true,
    observacoes: 'Comunicado à vigilância sanitária sobre a ocorrência. Prazo legal de 30 dias para resolução.',
    createdAt: '2025-03-17T07:30:00.000Z',
    updatedAt: '2025-03-19T16:00:00.000Z',
  },
  {
    id: 'mock-014',
    pedido: 'PED-2025-0014',
    lote: 'LT-009',
    dataEmissao: '2025-03-19',
    cliente: 'Banco Nacional do Desenvolvimento',
    cidadeUF: 'Rio de Janeiro/RJ',
    estado: 'RJ',
    nfAt: 'NFAT-10014',
    nfVenda: 'NFV-56789',
    item: 'IT-2580',
    descricaoItem: 'Divisória Modular com Vidro Duplo 6+6mm - 80m²',
    quantidade: 1,
    causaAssistencia: 'Perfil de união entre módulos com empeno dificultando vedação adequada',
    acoesCorretivas: 'Substituição dos perfis empenos e revisão do alinhamento de toda a divisória',
    motivoAssistencia: 'Defeito de Fabricação',
    motoristaResponsavel: 'Renato Carvalho',
    setor: 'Técnico',
    observacaoPedido: 'Acesso restrito. Credenciar todos os funcionários com antecedência mínima de 48h.',
    dataFinalizacao: '',
    status: 'Aguardando Cliente',
    modoEnvio: 'Frota Própria',
    emitirRncPdcva: false,
    observacoes: 'Aguardando aprovação do setor de segurança patrimonial para credenciamento da equipe.',
    createdAt: '2025-03-19T09:00:00.000Z',
    updatedAt: '2025-03-21T14:00:00.000Z',
  },
  {
    id: 'mock-015',
    pedido: 'PED-2025-0015',
    lote: 'LT-009',
    dataEmissao: '2025-03-21',
    cliente: 'Atacadão Distribuidor Nordeste',
    cidadeUF: 'Teresina/PI',
    estado: 'PI',
    nfAt: '',
    nfVenda: 'NFV-56901',
    item: 'IT-3390',
    descricaoItem: 'Portão Basculante em Alumínio - 4,00x3,20m',
    quantidade: 2,
    causaAssistencia: 'Motor de acionamento com superaquecimento após 5 acionamentos consecutivos',
    acoesCorretivas: '',
    motivoAssistencia: 'Defeito de Fabricação',
    motoristaResponsavel: '',
    setor: 'Técnico',
    observacaoPedido: 'Portão de acesso de caminhões. Alta demanda de uso — mais de 50 acionamentos/dia.',
    dataFinalizacao: '',
    status: 'Aberto',
    modoEnvio: '',
    emitirRncPdcva: false,
    observacoes: 'Abertura recente. Aguardando designação de técnico especialista em automação.',
    createdAt: '2025-03-21T11:00:00.000Z',
    updatedAt: '2025-03-21T11:00:00.000Z',
  },
];
